template = "https://github.com/giellalt/template-lang-und"
rev_id = 306
template_sha = "f3e6a329b1ec285a2a4b0abe3f024861cdd4e876"

[replacements]
__GLOTTOLOG_ID__ = "ingr1248"
__REPO__ = "lang-izh"
__UND2C__ = "izh"
__UNDEFINED__ = "Ingrian"
__UND__ = "izh"
