template = "https://github.com/giellalt/template-lang-und"
rev_id = 319
template_sha = "eda7c8f2efa7f16917002a5cc15e57ab9ecf2d1a"

[replacements]
__GLOTTOLOG_ID__ = "ingr1248"
__REPO__ = "lang-izh"
__UND2C__ = "izh"
__UNDEFINED__ = "Ingrian"
__UND__ = "izh"
