template = "https://github.com/giellalt/template-lang-und"
rev_id = 283
template_sha = "bfef967c632b9041975725ec13da8c2dfe66b74e"

[replacements]
__GLOTTOLOG_ID__ = "ingr1248"
__REPO__ = "lang-izh"
__UND2C__ = "izh"
__UNDEFINED__ = "Ingrian"
__UND__ = "izh"
