[package]
name = "izh"
human_name = "Ingrian"
version = "0.1.0"

# Table of speller tag -> filename to include in the bundle
# filenames depends on specific project
[spellers.izh]
filename = "izh-mobile.zhfst"

# Table of bundles to generated
# key is the type of bundle
# Windows speller bundle require a uuid for the installer
[bundles.speller_win]
package = "speller-izh"
platform = "windows"
uuid = "5FDDEFE6-0BE4-4CD0-98EB-A063337A9789"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_macos]
pkg_id = "no.divvun.MacDivvun.izh"
package = "speller-izh"
platform = "macos"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_win_mso]
package = "speller-izh-mso"
platform = "windows"
uuid = "AE388B61-7415-4367-A3DE-B80AEB9DAAD7"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_mobile]
package = "speller-izh"
platform = "mobile"
repo = "https://pahkat.uit.no/main/"
